/*
 * generated by Xtext
 */
package uk.ac.standrews.graspide.grasp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraspDSLRuntimeModule extends uk.ac.standrews.graspide.grasp.AbstractGraspDSLRuntimeModule {

}
