package uk.ac.standrews.graspide.tests.junittests;

import com.google.inject.Inject;
import java.util.Map;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.generator.InMemoryFileSystemAccess;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import uk.ac.standrews.graspide.grasp.GraspDSLInjectorProvider;
import uk.ac.standrews.graspide.grasp.graspDSL.GraspSpecification;

/**
 * Tests the code generator for Rationale specifications
 */
@RunWith(XtextRunner.class)
@InjectWith(GraspDSLInjectorProvider.class)
@SuppressWarnings("all")
public class GraspRationaleCodeGeneratorTests {
  @Inject
  private IGenerator generatorTest;
  
  @Inject
  private ParseHelper<GraspSpecification> parseHelper;
  
  @Test
  public void testConnectorRationaleGenerator() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("architecture testArchitecture");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("rationale testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("reason \'#testReason\';");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate() {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("system testSystem {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("connector testConnector = testTemplate() because testRationale();");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final GraspSpecification model = this.parseHelper.parse(_builder);
      final InMemoryFileSystemAccess fileSystem = new InMemoryFileSystemAccess();
      Resource _eResource = model.eResource();
      this.generatorTest.doGenerate(_eResource, fileSystem);
      Map<String,CharSequence> _files = fileSystem.getFiles();
      InputOutput.<Map<String,CharSequence>>println(_files);
      Map<String,CharSequence> _files_1 = fileSystem.getFiles();
      int _size = _files_1.size();
      Assert.assertEquals(1, _size);
      Map<String,CharSequence> _files_2 = fileSystem.getFiles();
      boolean _containsKey = _files_2.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testConnector/package-info.java"));
      Assert.assertTrue(_containsKey);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("/**");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* testConnector package is created in mapping to the Connector element \'testConnector\'");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* Rationale for mapped element is testRationale");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*@generated");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*/");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("package testConnector;");
      _builder_1.newLine();
      String _string = _builder_1.toString();
      Map<String,CharSequence> _files_3 = fileSystem.getFiles();
      CharSequence _get = _files_3.get((IFileSystemAccess.DEFAULT_OUTPUT + "testConnector/package-info.java"));
      String _string_1 = _get.toString();
      Assert.assertEquals(_string, _string_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testComponentRationaleGenerator() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("architecture testArchitecture");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("rationale testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("reason \'#testReason\';");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate() {");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("system testSystem {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("component testComponent = testTemplate() because testRationale();");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final GraspSpecification model = this.parseHelper.parse(_builder);
      final InMemoryFileSystemAccess fileSystem = new InMemoryFileSystemAccess();
      Resource _eResource = model.eResource();
      this.generatorTest.doGenerate(_eResource, fileSystem);
      Map<String,CharSequence> _files = fileSystem.getFiles();
      InputOutput.<Map<String,CharSequence>>println(_files);
      Map<String,CharSequence> _files_1 = fileSystem.getFiles();
      int _size = _files_1.size();
      Assert.assertEquals(1, _size);
      Map<String,CharSequence> _files_2 = fileSystem.getFiles();
      boolean _containsKey = _files_2.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent/package-info.java"));
      Assert.assertTrue(_containsKey);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("/**");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* testComponent package is created in mapping to the Component element \'testComponent\'");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* Rationale for mapped element is testRationale");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*@generated");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*/");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("package testComponent;");
      _builder_1.newLine();
      String _string = _builder_1.toString();
      Map<String,CharSequence> _files_3 = fileSystem.getFiles();
      CharSequence _get = _files_3.get((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent/package-info.java"));
      String _string_1 = _get.toString();
      Assert.assertEquals(_string, _string_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testLayerRationaleGenerator() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("architecture testArchitecture");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("rationale testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("reason \'#testReason\';");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("    ");
      _builder.append("system testSystem {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("layer testLayer because testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final GraspSpecification model = this.parseHelper.parse(_builder);
      final InMemoryFileSystemAccess fileSystem = new InMemoryFileSystemAccess();
      Resource _eResource = model.eResource();
      this.generatorTest.doGenerate(_eResource, fileSystem);
      Map<String,CharSequence> _files = fileSystem.getFiles();
      InputOutput.<Map<String,CharSequence>>println(_files);
      Map<String,CharSequence> _files_1 = fileSystem.getFiles();
      int _size = _files_1.size();
      Assert.assertEquals(1, _size);
      Map<String,CharSequence> _files_2 = fileSystem.getFiles();
      boolean _containsKey = _files_2.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testLayer/package-info.java"));
      Assert.assertTrue(_containsKey);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("/**");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* testLayer package is created in mapping to the Layer element \'testLayer\'");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* Rationale for mapped element is testRationale");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*@generated");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*/");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("package testLayer;");
      _builder_1.newLine();
      String _string = _builder_1.toString();
      Map<String,CharSequence> _files_3 = fileSystem.getFiles();
      CharSequence _get = _files_3.get((IFileSystemAccess.DEFAULT_OUTPUT + "testLayer/package-info.java"));
      String _string_1 = _get.toString();
      Assert.assertEquals(_string, _string_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testProvidesRationaleGenerator() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("architecture testArchitecture");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("rationale testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("reason \'#testReason\';");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("provides TestInterface because testRationale();");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("system testSystem {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("connector testConnector = testTemplate();");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final GraspSpecification model = this.parseHelper.parse(_builder);
      final InMemoryFileSystemAccess fileSystem = new InMemoryFileSystemAccess();
      Resource _eResource = model.eResource();
      this.generatorTest.doGenerate(_eResource, fileSystem);
      Map<String,CharSequence> _files = fileSystem.getFiles();
      InputOutput.<Map<String,CharSequence>>println(_files);
      Map<String,CharSequence> _files_1 = fileSystem.getFiles();
      int _size = _files_1.size();
      Assert.assertEquals(2, _size);
      Map<String,CharSequence> _files_2 = fileSystem.getFiles();
      boolean _containsKey = _files_2.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testConnector/TestInterface.java"));
      Assert.assertTrue(_containsKey);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("package testConnector;");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("/**");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* TestInterface interface is created in mapping to the Provides element \'testConnector.TestInterface\'");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* Rationale for mapped element is testRationale");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*@generated");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*/");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("public interface TestInterface {");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      String _string = _builder_1.toString();
      Map<String,CharSequence> _files_3 = fileSystem.getFiles();
      CharSequence _get = _files_3.get((IFileSystemAccess.DEFAULT_OUTPUT + "testConnector/TestInterface.java"));
      String _string_1 = _get.toString();
      Assert.assertEquals(_string, _string_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testLinkRationaleGenerator() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("architecture testArchitecture");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("rationale testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("reason \'#testReason\';");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate1() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("provides TestInterface;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate2() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("requires TestInterface;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("system testSystem {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("component testComponent1 = testTemplate1();");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("component testComponent2 = testTemplate2();");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("link testComponent2.TestInterface to testComponent1.TestInterface because testRationale();");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final GraspSpecification model = this.parseHelper.parse(_builder);
      final InMemoryFileSystemAccess fileSystem = new InMemoryFileSystemAccess();
      Resource _eResource = model.eResource();
      this.generatorTest.doGenerate(_eResource, fileSystem);
      Map<String,CharSequence> _files = fileSystem.getFiles();
      InputOutput.<Map<String,CharSequence>>println(_files);
      Map<String,CharSequence> _files_1 = fileSystem.getFiles();
      int _size = _files_1.size();
      Assert.assertEquals(4, _size);
      Map<String,CharSequence> _files_2 = fileSystem.getFiles();
      boolean _containsKey = _files_2.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent1/TestInterface.java"));
      Assert.assertTrue(_containsKey);
      Map<String,CharSequence> _files_3 = fileSystem.getFiles();
      boolean _containsKey_1 = _files_3.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent2/TestInterface.java"));
      Assert.assertTrue(_containsKey_1);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("package testComponent2;");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("/**");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* TestInterface interface is created in mapping to the Requires element \'testComponent2.TestInterface\'");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*@generated");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*/");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("interface TestInterface {");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("void setRequiredDependencies(testComponent1.TestInterface testInterface);");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("// Rationale for the Configuration is testRationale");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      String _string = _builder_1.toString();
      Map<String,CharSequence> _files_4 = fileSystem.getFiles();
      CharSequence _get = _files_4.get((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent2/TestInterface.java"));
      String _string_1 = _get.toString();
      Assert.assertEquals(_string, _string_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void testRequiresRationaleGenerator() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("architecture testArchitecture");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("rationale testRationale() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("reason \'#testReason\';");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate1() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("provides TestInterface;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("template testTemplate2() {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("requires TestInterface because testRationale();");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("system testSystem {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("component testComponent1 = testTemplate1();");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("component testComponent2 = testTemplate2();");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("link testComponent2.TestInterface to testComponent1.TestInterface;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final GraspSpecification model = this.parseHelper.parse(_builder);
      final InMemoryFileSystemAccess fileSystem = new InMemoryFileSystemAccess();
      Resource _eResource = model.eResource();
      this.generatorTest.doGenerate(_eResource, fileSystem);
      Map<String,CharSequence> _files = fileSystem.getFiles();
      InputOutput.<Map<String,CharSequence>>println(_files);
      Map<String,CharSequence> _files_1 = fileSystem.getFiles();
      int _size = _files_1.size();
      Assert.assertEquals(4, _size);
      Map<String,CharSequence> _files_2 = fileSystem.getFiles();
      boolean _containsKey = _files_2.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent1/TestInterface.java"));
      Assert.assertTrue(_containsKey);
      Map<String,CharSequence> _files_3 = fileSystem.getFiles();
      boolean _containsKey_1 = _files_3.containsKey((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent2/TestInterface.java"));
      Assert.assertTrue(_containsKey_1);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("package testComponent2;");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("/**");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* TestInterface interface is created in mapping to the Requires element \'testComponent2.TestInterface\'");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("* Rationale for require Interface is testRationale");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*@generated");
      _builder_1.newLine();
      _builder_1.append(" ");
      _builder_1.append("*/");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("interface TestInterface {");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("void setRequiredDependencies(testComponent1.TestInterface testInterface);");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      String _string = _builder_1.toString();
      Map<String,CharSequence> _files_4 = fileSystem.getFiles();
      CharSequence _get = _files_4.get((IFileSystemAccess.DEFAULT_OUTPUT + "testComponent2/TestInterface.java"));
      String _string_1 = _get.toString();
      Assert.assertEquals(_string, _string_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
