/*
* generated by Xtext
*/
package uk.ac.standrews.graspide.grasp;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GraspDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return uk.ac.standrews.graspide.grasp.ui.internal.GraspDSLActivator.getInstance().getInjector("uk.ac.standrews.graspide.grasp.GraspDSL");
	}
	
}
