/*
* generated by Xtext
*/
package uk.ac.standrews.graspide.grasp.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import uk.ac.standrews.graspide.grasp.services.GraspDSLGrammarAccess;

public class GraspDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private GraspDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected uk.ac.standrews.graspide.grasp.ui.contentassist.antlr.internal.InternalGraspDSLParser createParser() {
		uk.ac.standrews.graspide.grasp.ui.contentassist.antlr.internal.InternalGraspDSLParser result = new uk.ac.standrews.graspide.grasp.ui.contentassist.antlr.internal.InternalGraspDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDeclarationAccess().getAlternatives(), "rule__Declaration__Alternatives");
					put(grammarAccess.getRequirementOrQualityAccess().getAlternatives(), "rule__RequirementOrQuality__Alternatives");
					put(grammarAccess.getReasonAccess().getAlternatives_2(), "rule__Reason__Alternatives_2");
					put(grammarAccess.getTemplateConstituentAccess().getAlternatives(), "rule__TemplateConstituent__Alternatives");
					put(grammarAccess.getProvidesAccess().getAlternatives_5(), "rule__Provides__Alternatives_5");
					put(grammarAccess.getRequiresAccess().getAlternatives_4(), "rule__Requires__Alternatives_4");
					put(grammarAccess.getSystemConstituentAccess().getAlternatives(), "rule__SystemConstituent__Alternatives");
					put(grammarAccess.getCompositionalAccess().getAlternatives(), "rule__Compositional__Alternatives");
					put(grammarAccess.getLayerConstituentAccess().getAlternatives(), "rule__LayerConstituent__Alternatives");
					put(grammarAccess.getComponentAccess().getAlternatives_8(), "rule__Component__Alternatives_8");
					put(grammarAccess.getConnectorAccess().getAlternatives_8(), "rule__Connector__Alternatives_8");
					put(grammarAccess.getInstantiableConstituentAccess().getAlternatives(), "rule__InstantiableConstituent__Alternatives");
					put(grammarAccess.getLinkAccess().getAlternatives_6(), "rule__Link__Alternatives_6");
					put(grammarAccess.getLinkConsumerExpressionAccess().getRightConsumerAlternatives_1_1_0(), "rule__LinkConsumerExpression__RightConsumerAlternatives_1_1_0");
					put(grammarAccess.getLinkConsumerPartAccess().getAlternatives(), "rule__LinkConsumerPart__Alternatives");
					put(grammarAccess.getLinkProvidersAccess().getRightProviderAlternatives_1_1_0(), "rule__LinkProviders__RightProviderAlternatives_1_1_0");
					put(grammarAccess.getLinkProviderPartAccess().getAlternatives(), "rule__LinkProviderPart__Alternatives");
					put(grammarAccess.getEqualityExpressionAccess().getOpAlternatives_1_0_0(), "rule__EqualityExpression__OpAlternatives_1_0_0");
					put(grammarAccess.getRelationalExpressionAccess().getOpAlternatives_1_0_0(), "rule__RelationalExpression__OpAlternatives_1_0_0");
					put(grammarAccess.getAdditiveExpressionAccess().getOpAlternatives_1_0_0(), "rule__AdditiveExpression__OpAlternatives_1_0_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getOpAlternatives_1_0_0(), "rule__MultiplicativeExpression__OpAlternatives_1_0_0");
					put(grammarAccess.getUnaryExpressionAccess().getOpAlternatives_0_0(), "rule__UnaryExpression__OpAlternatives_0_0");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getMemberPartAccess().getAlternatives(), "rule__MemberPart__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getBOOLEAN_LITERALAccess().getAlternatives(), "rule__BOOLEAN_LITERAL__Alternatives");
					put(grammarAccess.getArchitectureAccess().getGroup(), "rule__Architecture__Group__0");
					put(grammarAccess.getArchitectureBodyAccess().getGroup(), "rule__ArchitectureBody__Group__0");
					put(grammarAccess.getDeclarationStartAccess().getGroup(), "rule__DeclarationStart__Group__0");
					put(grammarAccess.getDeclarationStartAccess().getGroup_1(), "rule__DeclarationStart__Group_1__0");
					put(grammarAccess.getDeclarationEndAccess().getGroup(), "rule__DeclarationEnd__Group__0");
					put(grammarAccess.getDeclarationEndAccess().getGroup_1(), "rule__DeclarationEnd__Group_1__0");
					put(grammarAccess.getRequirementAccess().getGroup(), "rule__Requirement__Group__0");
					put(grammarAccess.getRequirementAccess().getGroup_2(), "rule__Requirement__Group_2__0");
					put(grammarAccess.getQattributeAccess().getGroup(), "rule__Qattribute__Group__0");
					put(grammarAccess.getQattributeAccess().getGroup_2(), "rule__Qattribute__Group_2__0");
					put(grammarAccess.getRationaleAccess().getGroup(), "rule__Rationale__Group__0");
					put(grammarAccess.getRationaleAccess().getGroup_5(), "rule__Rationale__Group_5__0");
					put(grammarAccess.getReasonAccess().getGroup(), "rule__Reason__Group__0");
					put(grammarAccess.getTemplateAccess().getGroup(), "rule__Template__Group__0");
					put(grammarAccess.getTemplateAccess().getGroup_2(), "rule__Template__Group_2__0");
					put(grammarAccess.getTemplateAccess().getGroup_6(), "rule__Template__Group_6__0");
					put(grammarAccess.getTemplateAccess().getGroup_8(), "rule__Template__Group_8__0");
					put(grammarAccess.getProvidesAccess().getGroup(), "rule__Provides__Group__0");
					put(grammarAccess.getProvidesAccess().getGroup_2(), "rule__Provides__Group_2__0");
					put(grammarAccess.getProvidesAccess().getGroup_5_0(), "rule__Provides__Group_5_0__0");
					put(grammarAccess.getProvidesConstituentAccess().getGroup(), "rule__ProvidesConstituent__Group__0");
					put(grammarAccess.getRequiresAccess().getGroup(), "rule__Requires__Group__0");
					put(grammarAccess.getRequiresAccess().getGroup_4_0(), "rule__Requires__Group_4_0__0");
					put(grammarAccess.getRequiresConstituentAccess().getGroup(), "rule__RequiresConstituent__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup_2(), "rule__Property__Group_2__0");
					put(grammarAccess.getCheckAccess().getGroup(), "rule__Check__Group__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getSystemAccess().getGroup_4(), "rule__System__Group_4__0");
					put(grammarAccess.getLayerAccess().getGroup(), "rule__Layer__Group__0");
					put(grammarAccess.getLayerAccess().getGroup_2(), "rule__Layer__Group_2__0");
					put(grammarAccess.getLayerAccess().getGroup_2_2(), "rule__Layer__Group_2_2__0");
					put(grammarAccess.getLayerAccess().getGroup_5(), "rule__Layer__Group_5__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_8_0(), "rule__Component__Group_8_0__0");
					put(grammarAccess.getComponentAccess().getGroup_8_0_1(), "rule__Component__Group_8_0_1__0");
					put(grammarAccess.getConnectorAccess().getGroup(), "rule__Connector__Group__0");
					put(grammarAccess.getConnectorAccess().getGroup_8_0(), "rule__Connector__Group_8_0__0");
					put(grammarAccess.getConnectorAccess().getGroup_8_0_1(), "rule__Connector__Group_8_0_1__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_6_0(), "rule__Link__Group_6_0__0");
					put(grammarAccess.getLinkConstituentAccess().getGroup(), "rule__LinkConstituent__Group__0");
					put(grammarAccess.getLinkConsumerExpressionAccess().getGroup(), "rule__LinkConsumerExpression__Group__0");
					put(grammarAccess.getLinkConsumerExpressionAccess().getGroup_1(), "rule__LinkConsumerExpression__Group_1__0");
					put(grammarAccess.getLinkProvidersListAccess().getGroup(), "rule__LinkProvidersList__Group__0");
					put(grammarAccess.getLinkProvidersListAccess().getGroup_1(), "rule__LinkProvidersList__Group_1__0");
					put(grammarAccess.getLinkProvidersAccess().getGroup(), "rule__LinkProviders__Group__0");
					put(grammarAccess.getLinkProvidersAccess().getGroup_1(), "rule__LinkProviders__Group_1__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getNameValueAccess().getGroup(), "rule__NameValue__Group__0");
					put(grammarAccess.getNameValuesAccess().getGroup(), "rule__NameValues__Group__0");
					put(grammarAccess.getNameValuesAccess().getGroup_1(), "rule__NameValues__Group_1__0");
					put(grammarAccess.getSupportsClauseAccess().getGroup(), "rule__SupportsClause__Group__0");
					put(grammarAccess.getSupportsClauseAccess().getGroup_2(), "rule__SupportsClause__Group_2__0");
					put(grammarAccess.getInhibitsClauseAccess().getGroup(), "rule__InhibitsClause__Group__0");
					put(grammarAccess.getInhibitsClauseAccess().getGroup_2(), "rule__InhibitsClause__Group_2__0");
					put(grammarAccess.getBecauseClauseAccess().getGroup(), "rule__BecauseClause__Group__0");
					put(grammarAccess.getBecauseClauseAccess().getGroup_2(), "rule__BecauseClause__Group_2__0");
					put(grammarAccess.getBecauseCausalcontextAccess().getGroup(), "rule__BecauseCausalcontext__Group__0");
					put(grammarAccess.getParameterListAccess().getGroup(), "rule__ParameterList__Group__0");
					put(grammarAccess.getParameterListAccess().getGroup_1(), "rule__ParameterList__Group_1__0");
					put(grammarAccess.getArgumentListAccess().getGroup(), "rule__ArgumentList__Group__0");
					put(grammarAccess.getArgumentListAccess().getGroup_1(), "rule__ArgumentList__Group_1__0");
					put(grammarAccess.getSubsetofExpressionAccess().getGroup(), "rule__SubsetofExpression__Group__0");
					put(grammarAccess.getSubsetofExpressionAccess().getGroup_1(), "rule__SubsetofExpression__Group_1__0");
					put(grammarAccess.getLogicalOrExpressionAccess().getGroup(), "rule__LogicalOrExpression__Group__0");
					put(grammarAccess.getLogicalOrExpressionAccess().getGroup_1(), "rule__LogicalOrExpression__Group_1__0");
					put(grammarAccess.getLogicalAndExpressionAccess().getGroup(), "rule__LogicalAndExpression__Group__0");
					put(grammarAccess.getLogicalAndExpressionAccess().getGroup_1(), "rule__LogicalAndExpression__Group_1__0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getGroup(), "rule__BitwiseOrExpression__Group__0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getGroup_1(), "rule__BitwiseOrExpression__Group_1__0");
					put(grammarAccess.getBitwiseXorExpressionAccess().getGroup(), "rule__BitwiseXorExpression__Group__0");
					put(grammarAccess.getBitwiseXorExpressionAccess().getGroup_1(), "rule__BitwiseXorExpression__Group_1__0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getGroup(), "rule__BitwiseAndExpression__Group__0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getGroup_1(), "rule__BitwiseAndExpression__Group_1__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup(), "rule__EqualityExpression__Group__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup_1(), "rule__EqualityExpression__Group_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_1(), "rule__RelationalExpression__Group_1__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup(), "rule__AdditiveExpression__Group__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_1(), "rule__AdditiveExpression__Group_1__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup(), "rule__MultiplicativeExpression__Group__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1(), "rule__MultiplicativeExpression__Group_1__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup(), "rule__UnaryExpression__Group__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_0(), "rule__PrimaryExpression__Group_0__0");
					put(grammarAccess.getMemberExpressionAccess().getGroup(), "rule__MemberExpression__Group__0");
					put(grammarAccess.getMemberExpressionAccess().getGroup_1(), "rule__MemberExpression__Group_1__0");
					put(grammarAccess.getMemberPartAccess().getGroup_1(), "rule__MemberPart__Group_1__0");
					put(grammarAccess.getMemberPartAccess().getGroup_2(), "rule__MemberPart__Group_2__0");
					put(grammarAccess.getMemberPartAccess().getGroup_3(), "rule__MemberPart__Group_3__0");
					put(grammarAccess.getMemberArgumentsAccess().getGroup(), "rule__MemberArguments__Group__0");
					put(grammarAccess.getMemberArgumentsAccess().getGroup_1(), "rule__MemberArguments__Group_1__0");
					put(grammarAccess.getLiteralAccess().getGroup_1(), "rule__Literal__Group_1__0");
					put(grammarAccess.getLiteralAccess().getGroup_2(), "rule__Literal__Group_2__0");
					put(grammarAccess.getLiteralAccess().getGroup_4(), "rule__Literal__Group_4__0");
					put(grammarAccess.getSetLiteralAccess().getGroup(), "rule__SetLiteral__Group__0");
					put(grammarAccess.getSetLiteralAccess().getGroup_2(), "rule__SetLiteral__Group_2__0");
					put(grammarAccess.getSetLiteralAccess().getGroup_2_1(), "rule__SetLiteral__Group_2_1__0");
					put(grammarAccess.getREAL_LITERALAccess().getGroup(), "rule__REAL_LITERAL__Group__0");
					put(grammarAccess.getBOOLEAN_LITERALAccess().getGroup_0(), "rule__BOOLEAN_LITERAL__Group_0__0");
					put(grammarAccess.getBOOLEAN_LITERALAccess().getGroup_1(), "rule__BOOLEAN_LITERAL__Group_1__0");
					put(grammarAccess.getBOOLEAN_LITERALAccess().getGroup_2(), "rule__BOOLEAN_LITERAL__Group_2__0");
					put(grammarAccess.getGraspSpecificationAccess().getArchitectureAssignment(), "rule__GraspSpecification__ArchitectureAssignment");
					put(grammarAccess.getArchitectureAccess().getAnnotationAssignment_0(), "rule__Architecture__AnnotationAssignment_0");
					put(grammarAccess.getArchitectureAccess().getNameAssignment_2(), "rule__Architecture__NameAssignment_2");
					put(grammarAccess.getArchitectureAccess().getArchitecutrebodyAssignment_4(), "rule__Architecture__ArchitecutrebodyAssignment_4");
					put(grammarAccess.getArchitectureBodyAccess().getAnnotationAssignment_0(), "rule__ArchitectureBody__AnnotationAssignment_0");
					put(grammarAccess.getArchitectureBodyAccess().getDeclarationStartAssignment_1(), "rule__ArchitectureBody__DeclarationStartAssignment_1");
					put(grammarAccess.getArchitectureBodyAccess().getSystemAssignment_2(), "rule__ArchitectureBody__SystemAssignment_2");
					put(grammarAccess.getArchitectureBodyAccess().getDeclarationEndAssignment_3(), "rule__ArchitectureBody__DeclarationEndAssignment_3");
					put(grammarAccess.getDeclarationStartAccess().getDeclarationAssignment_1_0(), "rule__DeclarationStart__DeclarationAssignment_1_0");
					put(grammarAccess.getDeclarationStartAccess().getAnnotationAssignment_1_1(), "rule__DeclarationStart__AnnotationAssignment_1_1");
					put(grammarAccess.getDeclarationEndAccess().getAnnotationAssignment_1_0(), "rule__DeclarationEnd__AnnotationAssignment_1_0");
					put(grammarAccess.getDeclarationEndAccess().getDeclarationAssignment_1_1(), "rule__DeclarationEnd__DeclarationAssignment_1_1");
					put(grammarAccess.getRequirementAccess().getNameAssignment_1(), "rule__Requirement__NameAssignment_1");
					put(grammarAccess.getRequirementAccess().getStringLiteralAssignment_2_1(), "rule__Requirement__StringLiteralAssignment_2_1");
					put(grammarAccess.getQattributeAccess().getNameAssignment_1(), "rule__Qattribute__NameAssignment_1");
					put(grammarAccess.getQattributeAccess().getExpressionAssignment_2_1(), "rule__Qattribute__ExpressionAssignment_2_1");
					put(grammarAccess.getQattributeAccess().getSupportsClauseAssignment_3(), "rule__Qattribute__SupportsClauseAssignment_3");
					put(grammarAccess.getRationaleAccess().getNameAssignment_1(), "rule__Rationale__NameAssignment_1");
					put(grammarAccess.getRationaleAccess().getParameterListAssignment_3(), "rule__Rationale__ParameterListAssignment_3");
					put(grammarAccess.getRationaleAccess().getSuperRationaleAssignment_5_1(), "rule__Rationale__SuperRationaleAssignment_5_1");
					put(grammarAccess.getRationaleAccess().getReasonAssignment_7(), "rule__Rationale__ReasonAssignment_7");
					put(grammarAccess.getReasonAccess().getReasonAnnotationAssignment_0(), "rule__Reason__ReasonAnnotationAssignment_0");
					put(grammarAccess.getReasonAccess().getExpressionAssignment_2_0(), "rule__Reason__ExpressionAssignment_2_0");
					put(grammarAccess.getReasonAccess().getSupportsClauseAssignment_2_1(), "rule__Reason__SupportsClauseAssignment_2_1");
					put(grammarAccess.getReasonAccess().getInhibitsClauseAssignment_3(), "rule__Reason__InhibitsClauseAssignment_3");
					put(grammarAccess.getTemplateAccess().getNameAssignment_1(), "rule__Template__NameAssignment_1");
					put(grammarAccess.getTemplateAccess().getIntegerLiteralAssignment_2_1(), "rule__Template__IntegerLiteralAssignment_2_1");
					put(grammarAccess.getTemplateAccess().getParameterListAssignment_4(), "rule__Template__ParameterListAssignment_4");
					put(grammarAccess.getTemplateAccess().getSuperTemplateAssignment_6_1(), "rule__Template__SuperTemplateAssignment_6_1");
					put(grammarAccess.getTemplateAccess().getTemplateAnnotationAssignment_8_0(), "rule__Template__TemplateAnnotationAssignment_8_0");
					put(grammarAccess.getTemplateAccess().getTemplateConstituentAssignment_8_1(), "rule__Template__TemplateConstituentAssignment_8_1");
					put(grammarAccess.getProvidesAccess().getNameAssignment_1(), "rule__Provides__NameAssignment_1");
					put(grammarAccess.getProvidesAccess().getValueAssignment_2_1(), "rule__Provides__ValueAssignment_2_1");
					put(grammarAccess.getProvidesAccess().getTypeAssignment_3(), "rule__Provides__TypeAssignment_3");
					put(grammarAccess.getProvidesAccess().getBecauseClauseAssignment_4(), "rule__Provides__BecauseClauseAssignment_4");
					put(grammarAccess.getProvidesAccess().getProvidesConstituentAssignment_5_0_1(), "rule__Provides__ProvidesConstituentAssignment_5_0_1");
					put(grammarAccess.getProvidesConstituentAccess().getProvidesAnnotationAssignment_0(), "rule__ProvidesConstituent__ProvidesAnnotationAssignment_0");
					put(grammarAccess.getProvidesConstituentAccess().getCheckAssignment_1(), "rule__ProvidesConstituent__CheckAssignment_1");
					put(grammarAccess.getRequiresAccess().getTypeAssignment_1(), "rule__Requires__TypeAssignment_1");
					put(grammarAccess.getRequiresAccess().getValueAssignment_2(), "rule__Requires__ValueAssignment_2");
					put(grammarAccess.getRequiresAccess().getBecauseRequiresClauseAssignment_3(), "rule__Requires__BecauseRequiresClauseAssignment_3");
					put(grammarAccess.getRequiresAccess().getRequiresConstituentAssignment_4_0_1(), "rule__Requires__RequiresConstituentAssignment_4_0_1");
					put(grammarAccess.getRequiresConstituentAccess().getRequiresAnnotationAssignment_0(), "rule__RequiresConstituent__RequiresAnnotationAssignment_0");
					put(grammarAccess.getRequiresConstituentAccess().getCheckAssignment_1(), "rule__RequiresConstituent__CheckAssignment_1");
					put(grammarAccess.getPropertyAccess().getNameAssignment_1(), "rule__Property__NameAssignment_1");
					put(grammarAccess.getPropertyAccess().getExpressionAssignment_2_1(), "rule__Property__ExpressionAssignment_2_1");
					put(grammarAccess.getPropertyAccess().getBecauseClauseAssignment_3(), "rule__Property__BecauseClauseAssignment_3");
					put(grammarAccess.getCheckAccess().getExpressionAssignment_1(), "rule__Check__ExpressionAssignment_1");
					put(grammarAccess.getCheckAccess().getBecauseClauseAssignment_2(), "rule__Check__BecauseClauseAssignment_2");
					put(grammarAccess.getSystemAccess().getNameAssignment_1(), "rule__System__NameAssignment_1");
					put(grammarAccess.getSystemAccess().getBecauseClauseAssignment_2(), "rule__System__BecauseClauseAssignment_2");
					put(grammarAccess.getSystemAccess().getSystemAnnotationAssignment_4_0(), "rule__System__SystemAnnotationAssignment_4_0");
					put(grammarAccess.getSystemAccess().getSystemConstituentAssignment_4_1(), "rule__System__SystemConstituentAssignment_4_1");
					put(grammarAccess.getLayerAccess().getNameAssignment_1(), "rule__Layer__NameAssignment_1");
					put(grammarAccess.getLayerAccess().getSuperLayerAssignment_2_1(), "rule__Layer__SuperLayerAssignment_2_1");
					put(grammarAccess.getLayerAccess().getSuperLayerAssignment_2_2_1(), "rule__Layer__SuperLayerAssignment_2_2_1");
					put(grammarAccess.getLayerAccess().getBecauseClauseAssignment_3(), "rule__Layer__BecauseClauseAssignment_3");
					put(grammarAccess.getLayerAccess().getLayerAnnotationAssignment_5_0(), "rule__Layer__LayerAnnotationAssignment_5_0");
					put(grammarAccess.getLayerAccess().getLayerConstituentAssignment_5_1(), "rule__Layer__LayerConstituentAssignment_5_1");
					put(grammarAccess.getComponentAccess().getNameAssignment_1(), "rule__Component__NameAssignment_1");
					put(grammarAccess.getComponentAccess().getValueAssignment_3(), "rule__Component__ValueAssignment_3");
					put(grammarAccess.getComponentAccess().getArgumentListAssignment_5(), "rule__Component__ArgumentListAssignment_5");
					put(grammarAccess.getComponentAccess().getBecauseClauseAssignment_7(), "rule__Component__BecauseClauseAssignment_7");
					put(grammarAccess.getComponentAccess().getAnnotationAssignment_8_0_1_0(), "rule__Component__AnnotationAssignment_8_0_1_0");
					put(grammarAccess.getComponentAccess().getInstantiableConstituentAssignment_8_0_1_1(), "rule__Component__InstantiableConstituentAssignment_8_0_1_1");
					put(grammarAccess.getConnectorAccess().getNameAssignment_1(), "rule__Connector__NameAssignment_1");
					put(grammarAccess.getConnectorAccess().getValueAssignment_3(), "rule__Connector__ValueAssignment_3");
					put(grammarAccess.getConnectorAccess().getArgumentListAssignment_5(), "rule__Connector__ArgumentListAssignment_5");
					put(grammarAccess.getConnectorAccess().getBecauseClauseAssignment_7(), "rule__Connector__BecauseClauseAssignment_7");
					put(grammarAccess.getConnectorAccess().getAnnotationAssignment_8_0_1_0(), "rule__Connector__AnnotationAssignment_8_0_1_0");
					put(grammarAccess.getConnectorAccess().getInstantiableConstituentAssignment_8_0_1_1(), "rule__Connector__InstantiableConstituentAssignment_8_0_1_1");
					put(grammarAccess.getLinkAccess().getTypeAssignment_1(), "rule__Link__TypeAssignment_1");
					put(grammarAccess.getLinkAccess().getLinkConsumerAssignment_2(), "rule__Link__LinkConsumerAssignment_2");
					put(grammarAccess.getLinkAccess().getLinkProvidersAssignment_4(), "rule__Link__LinkProvidersAssignment_4");
					put(grammarAccess.getLinkAccess().getBecauseClauseAssignment_5(), "rule__Link__BecauseClauseAssignment_5");
					put(grammarAccess.getLinkAccess().getLinkConstituentAssignment_6_0_1(), "rule__Link__LinkConstituentAssignment_6_0_1");
					put(grammarAccess.getLinkConstituentAccess().getAnnotationAssignment_0(), "rule__LinkConstituent__AnnotationAssignment_0");
					put(grammarAccess.getLinkConstituentAccess().getCheckAssignment_1(), "rule__LinkConstituent__CheckAssignment_1");
					put(grammarAccess.getLinkConsumerExpressionAccess().getConsumerAssignment_0(), "rule__LinkConsumerExpression__ConsumerAssignment_0");
					put(grammarAccess.getLinkConsumerExpressionAccess().getRightConsumerAssignment_1_1(), "rule__LinkConsumerExpression__RightConsumerAssignment_1_1");
					put(grammarAccess.getLinkProvidersListAccess().getProvidersAssignment_0(), "rule__LinkProvidersList__ProvidersAssignment_0");
					put(grammarAccess.getLinkProvidersListAccess().getProvidersAssignment_1_1(), "rule__LinkProvidersList__ProvidersAssignment_1_1");
					put(grammarAccess.getLinkProvidersAccess().getProviderAssignment_0(), "rule__LinkProviders__ProviderAssignment_0");
					put(grammarAccess.getLinkProvidersAccess().getRightProviderAssignment_1_1(), "rule__LinkProviders__RightProviderAssignment_1_1");
					put(grammarAccess.getAnnotationAccess().getAnnotationAssignment_1(), "rule__Annotation__AnnotationAssignment_1");
					put(grammarAccess.getAnnotationAccess().getValueAssignment_3(), "rule__Annotation__ValueAssignment_3");
					put(grammarAccess.getNameValueAccess().getNamePairAssignment_0(), "rule__NameValue__NamePairAssignment_0");
					put(grammarAccess.getNameValueAccess().getValuePairAssignment_2(), "rule__NameValue__ValuePairAssignment_2");
					put(grammarAccess.getNameValuesAccess().getMembersAssignment_0(), "rule__NameValues__MembersAssignment_0");
					put(grammarAccess.getNameValuesAccess().getMembersAssignment_1_1(), "rule__NameValues__MembersAssignment_1_1");
					put(grammarAccess.getSupportsClauseAccess().getValueAssignment_1(), "rule__SupportsClause__ValueAssignment_1");
					put(grammarAccess.getSupportsClauseAccess().getValueAssignment_2_1(), "rule__SupportsClause__ValueAssignment_2_1");
					put(grammarAccess.getInhibitsClauseAccess().getValueAssignment_1(), "rule__InhibitsClause__ValueAssignment_1");
					put(grammarAccess.getInhibitsClauseAccess().getValueAssignment_2_1(), "rule__InhibitsClause__ValueAssignment_2_1");
					put(grammarAccess.getBecauseClauseAccess().getMembersAssignment_1(), "rule__BecauseClause__MembersAssignment_1");
					put(grammarAccess.getBecauseClauseAccess().getMembersAssignment_2_1(), "rule__BecauseClause__MembersAssignment_2_1");
					put(grammarAccess.getBecauseCausalcontextAccess().getValueAssignment_0(), "rule__BecauseCausalcontext__ValueAssignment_0");
					put(grammarAccess.getBecauseCausalcontextAccess().getArgumentListAssignment_2(), "rule__BecauseCausalcontext__ArgumentListAssignment_2");
					put(grammarAccess.getParameterListAccess().getNamesAssignment_0(), "rule__ParameterList__NamesAssignment_0");
					put(grammarAccess.getParameterListAccess().getNamesAssignment_1_1(), "rule__ParameterList__NamesAssignment_1_1");
					put(grammarAccess.getArgumentListAccess().getMembersAssignment_0(), "rule__ArgumentList__MembersAssignment_0");
					put(grammarAccess.getArgumentListAccess().getMembersAssignment_1_1(), "rule__ArgumentList__MembersAssignment_1_1");
					put(grammarAccess.getSubsetofExpressionAccess().getLogicalOrAssignment_0(), "rule__SubsetofExpression__LogicalOrAssignment_0");
					put(grammarAccess.getSubsetofExpressionAccess().getLogicalOrAssignment_1_1(), "rule__SubsetofExpression__LogicalOrAssignment_1_1");
					put(grammarAccess.getLogicalOrExpressionAccess().getLogicalAndAssignment_0(), "rule__LogicalOrExpression__LogicalAndAssignment_0");
					put(grammarAccess.getLogicalOrExpressionAccess().getLogicalAndAssignment_1_1(), "rule__LogicalOrExpression__LogicalAndAssignment_1_1");
					put(grammarAccess.getLogicalAndExpressionAccess().getBitwiseOrAssignment_0(), "rule__LogicalAndExpression__BitwiseOrAssignment_0");
					put(grammarAccess.getLogicalAndExpressionAccess().getBitwiseOrAssignment_1_1(), "rule__LogicalAndExpression__BitwiseOrAssignment_1_1");
					put(grammarAccess.getBitwiseOrExpressionAccess().getBitwiseXorAssignment_0(), "rule__BitwiseOrExpression__BitwiseXorAssignment_0");
					put(grammarAccess.getBitwiseOrExpressionAccess().getBitwiseXorAssignment_1_1(), "rule__BitwiseOrExpression__BitwiseXorAssignment_1_1");
					put(grammarAccess.getBitwiseXorExpressionAccess().getBitwiseAndAssignment_0(), "rule__BitwiseXorExpression__BitwiseAndAssignment_0");
					put(grammarAccess.getBitwiseXorExpressionAccess().getBitwiseAndAssignment_1_1(), "rule__BitwiseXorExpression__BitwiseAndAssignment_1_1");
					put(grammarAccess.getBitwiseAndExpressionAccess().getEqualityAssignment_0(), "rule__BitwiseAndExpression__EqualityAssignment_0");
					put(grammarAccess.getBitwiseAndExpressionAccess().getEqualityAssignment_1_1(), "rule__BitwiseAndExpression__EqualityAssignment_1_1");
					put(grammarAccess.getEqualityExpressionAccess().getRelationalAssignment_0(), "rule__EqualityExpression__RelationalAssignment_0");
					put(grammarAccess.getEqualityExpressionAccess().getOpAssignment_1_0(), "rule__EqualityExpression__OpAssignment_1_0");
					put(grammarAccess.getEqualityExpressionAccess().getRelationalAssignment_1_1(), "rule__EqualityExpression__RelationalAssignment_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getAdditiveAssignment_0(), "rule__RelationalExpression__AdditiveAssignment_0");
					put(grammarAccess.getRelationalExpressionAccess().getOpAssignment_1_0(), "rule__RelationalExpression__OpAssignment_1_0");
					put(grammarAccess.getRelationalExpressionAccess().getAdditiveAssignment_1_1(), "rule__RelationalExpression__AdditiveAssignment_1_1");
					put(grammarAccess.getAdditiveExpressionAccess().getMultiplicativeAssignment_0(), "rule__AdditiveExpression__MultiplicativeAssignment_0");
					put(grammarAccess.getAdditiveExpressionAccess().getOpAssignment_1_0(), "rule__AdditiveExpression__OpAssignment_1_0");
					put(grammarAccess.getAdditiveExpressionAccess().getMultiplicativeAssignment_1_1(), "rule__AdditiveExpression__MultiplicativeAssignment_1_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getUnaryAssignment_0(), "rule__MultiplicativeExpression__UnaryAssignment_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getOpAssignment_1_0(), "rule__MultiplicativeExpression__OpAssignment_1_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getUnaryAssignment_1_1(), "rule__MultiplicativeExpression__UnaryAssignment_1_1");
					put(grammarAccess.getUnaryExpressionAccess().getOpAssignment_0(), "rule__UnaryExpression__OpAssignment_0");
					put(grammarAccess.getUnaryExpressionAccess().getRightAssignment_1(), "rule__UnaryExpression__RightAssignment_1");
					put(grammarAccess.getMemberExpressionAccess().getMemberAssignment_0(), "rule__MemberExpression__MemberAssignment_0");
					put(grammarAccess.getMemberExpressionAccess().getMemberAssignment_1_1(), "rule__MemberExpression__MemberAssignment_1_1");
					put(grammarAccess.getMemberPartAccess().getNameAssignment_0(), "rule__MemberPart__NameAssignment_0");
					put(grammarAccess.getMemberPartAccess().getNameAssignment_1_0(), "rule__MemberPart__NameAssignment_1_0");
					put(grammarAccess.getMemberPartAccess().getMemberArgumentsAssignment_1_2(), "rule__MemberPart__MemberArgumentsAssignment_1_2");
					put(grammarAccess.getMemberArgumentsAccess().getExpressionAssignment_0(), "rule__MemberArguments__ExpressionAssignment_0");
					put(grammarAccess.getMemberArgumentsAccess().getExpressionAssignment_1_1(), "rule__MemberArguments__ExpressionAssignment_1_1");
					put(grammarAccess.getSetLiteralAccess().getLiteralAssignment_2_0(), "rule__SetLiteral__LiteralAssignment_2_0");
					put(grammarAccess.getSetLiteralAccess().getLiteralAssignment_2_1_1(), "rule__SetLiteral__LiteralAssignment_2_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			uk.ac.standrews.graspide.grasp.ui.contentassist.antlr.internal.InternalGraspDSLParser typedParser = (uk.ac.standrews.graspide.grasp.ui.contentassist.antlr.internal.InternalGraspDSLParser) parser;
			typedParser.entryRuleGraspSpecification();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GraspDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GraspDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
