/*
* generated by Xtext
*/
package uk.ac.standrews.graspide.grasp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.standrews.graspide.grasp.services.GraspDSLGrammarAccess;

public class GraspDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GraspDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected uk.ac.standrews.graspide.grasp.parser.antlr.internal.InternalGraspDSLParser createParser(XtextTokenStream stream) {
		return new uk.ac.standrews.graspide.grasp.parser.antlr.internal.InternalGraspDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GraspSpecification";
	}
	
	public GraspDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GraspDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
