/*
* generated by Xtext
*/
package uk.ac.standrews.graspide.grasp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraspDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("uk/ac/standrews/graspide/grasp/parser/antlr/internal/InternalGraspDSL.tokens");
	}
}
