/*
 * generated by Xtext
 */
package uk.ac.standrews.graspide.grasp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import uk.ac.standrews.graspide.grasp.ui.hover.GraspDocumentationProvider;
import uk.ac.standrews.graspide.grasp.ui.hover.GraspHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraspDSLUiModule extends uk.ac.standrews.graspide.grasp.ui.AbstractGraspDSLUiModule {
	public GraspDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return GraspHoverProvider.class;
    }
	 public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
	        return GraspDocumentationProvider.class;
	    }
//	 public Class<? extends org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage> bindLanguageRootPreferencePage() {
//	     return uk.ac.standrews.graspide.grasp.ui.ValidationPreferencesPage.class;
//	 }
}
