/*
 * generated by Xtext
 */
package uk.ac.standrews.graspide.grasp.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uk.ac.standrews.graspide.grasp.ui.internal.GraspDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraspDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GraspDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GraspDSLActivator.getInstance().getInjector(GraspDSLActivator.UK_AC_STANDREWS_GRASPIDE_GRASP_GRASPDSL);
	}
	
}
